### ISSUE TITLE
Make command inputs more humanly intuitive

### ISSUE THREAD

**Issue by han-gyeol** [CS2103AUG2016-T14-C1/main#41]
For example,
d/21-12-2016 -> 21th Dec 2016
s/1400 -> start at 2pm
p/1 -> priority: HIGH/MEDIUM/LOW

These things have low priority. We will try to implement when we have time.
Add more intuitive command cases in the comment!

**Comment by jsfr0st** [comment]
Completed making Date, Time and Priority more humanly intuitive.
